name: HTML Proofer

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  test:
    name: HTML Proofer
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Image Magick
        run: sudo apt-get update && sudo apt-get install imagemagick
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Jekyll build
        env:
          JEKYLL_ENV: production
        run: bundle exec jekyll build --destination _proof
      - name: HTML proofer
        env:
          JEKYLL_ENV: production
        run: bundle exec rake html_proofer
